// <auto-generated />
namespace MIS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class changeWeekendtypetoDateTim2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeWeekendtypetoDateTim2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811272126105_changeWeekendtypetoDateTim2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
